# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []


# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'layout accordion',
  'workspace 1',
  # 'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=6.0',
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 10

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
# cmd-h = []     # Disable "hide application"
# cmd-alt-h = [] # Disable "hide others"

shift-alt-c = 'close'
alt-q = 'close'

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-enter = 'exec-and-forget open -na Ghostty.app'
alt-b = 'exec-and-forget open -na Google\ Chrome.app'
alt-c = 'exec-and-forget open -na WhatsApp\ Web.app'
alt-y = 'exec-and-forget open -na Ghostty.app --args --command=yazi'
# alt-s = 'exec-and-forget $HOME/.local/bin/tmux-session-picker'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-f = 'fullscreen'
alt-shift-f = 'macos-native-fullscreen'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-w = 'layout accordion horizontal vertical'
alt-e = 'layout tiles horizontal vertical'         # 'layout toggle split' in i3

# alt-shift-space = 'layout floating tiling'
alt-t = 'layout floating tiling'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-ctrl-h = 'join-with left'
alt-shift-ctrl-j = 'join-with down'
alt-shift-ctrl-k = 'join-with up'
alt-shift-ctrl-l = 'join-with right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Resizing: See https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-shift-0 = 'balance-sizes'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-n = 'focus-monitor --wrap-around next'
alt-p = 'focus-monitor --wrap-around prev'

# Mode changes: See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-r = 'mode resize'
alt-shift-semicolon = 'mode service'

[workspace-to-monitor-force-assignment]
1 = 'secondary'

[mode.service.binding]
backspace = ['close-all-windows-but-current', 'mode main']
r = ['reload-config', 'mode main']
f = ['flatten-workspace-tree', 'mode main']
enter = 'mode main'
esc = 'mode main'

h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

[mode.resize.binding]
j = 'resize height +50'
k = 'resize height -50'
h = 'resize width -50'
l = 'resize width +50'
0 = ['balance-sizes', 'mode main']
minus = 'resize smart -50'
equal = 'resize smart +50'
enter = 'mode main'
esc = 'mode main'

# Callbacks
[[on-window-detected]]
if.app-id = 'net.battle.app'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.runningwithcrayons.Alfred-Preferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'Outlook'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 5'

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/etc/profiles/per-user/${USER}/bin:/run/current-system/sw/bin:${HOME}/.nix-profile/bin:${HOME}/.local/state/nix/profile/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'
