{ inputs, ... }:
{
  imports = [
    inputs.dms.homeModules.dank-material-shell
    inputs.dms.homeModules.niri
  ];

  programs.dank-material-shell = {
    enable = true;
    niri.includes = {
      enable = true; # Enable config includes hack. Enabled by default.
      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab"
        "binds"
        "colors"
        "layout"
        "outputs"
      ];
    };
  };
}
